
#### JAVA ####
# Assignment 4 Makefile
.PHONY : build view clean

.PHONY : build view clean

build :
	chmod u+x assn4.java
	chmod +x assn4
	chmod +x test.script
	javac assn4.java 

view :
	@\less assn4.java 

clean :
	@\rm *.class
