#/bin/bash

# init the register 
./assn4 init 15 = 5 2 0 0

# get a report to check thebalance of the register
./assn4 report

# make a purchase of $38 and give the balance
./assn4 purchase 38 = 0 0 0 2

# this change should fail because there are not enough singles to give back
./assn4 change 0 1 = 5
echo $?

# make another purchase
./assn4 purchase 20 = 0 0 0 1

# get another report should look like 58 : 73 = 3 2 0 3  
./assn4 report 

# make a change for $10 to 2*$5
./assn4 change 0 0 1 0 = 0 2 0 0

# get a report answer should be 58 : 73 = 3 0 1 3
./assn4 report

# add some singles 
./assn4 purchase 5 = 5 0 0 0

# enter a bad argument
./assn4 bad_argument
echo $?

# not enough money to make a purchase
./assn4 purchase 38 = 0 0 0 1
echo $?


